/* ============================================================
   Notation — the symbol library behind the Decoder.

   One entry per glyph: how it is said out loud, what it means,
   and the trap that makes it hard to read. The "watch" field is
   the point of the whole thing — most notation is not difficult,
   it is *overloaded*, and knowing which of three meanings is in
   play is the entire skill.

   domain: grammar | sets | algebra | calculus | probability |
           optimization | information | neural | inference
   level:  basic | mid | advanced
   ============================================================ */

window.NOTATION = [
  /* ---- grammar ---- */
  { g: "=", name: "Equals", say: "equals", domain: "grammar", level: "basic",
    means: "The two sides have the same value.",
    watch: "In papers it is often used for a *definition* where ≔ is meant. If the left side is a new name, it is a definition." },
  { g: "≔", name: "Defined as", say: "is defined as", domain: "grammar", level: "basic",
    means: "Introduces a name; the right side fixes what it means.",
    watch: "Directional. You cannot rearrange it the way you can an equation." },
  { g: "≡", name: "Equivalent", say: "is equivalent to", domain: "grammar", level: "mid",
    means: "An identity, an equivalence relation, or congruence.",
    watch: "How strong it is depends entirely on context — modular arithmetic and logic use it very differently." },
  { g: "≈", name: "Approximately equal", say: "is approximately", domain: "grammar", level: "basic",
    means: "Close enough for the purpose being argued.",
    watch: "Never quantified. If the bound matters, the paper owes you an explicit one." },
  { g: "∝", name: "Proportional to", say: "is proportional to", domain: "grammar", level: "mid",
    means: "Equal up to a constant factor that does not matter here.",
    watch: "Extremely common in Bayes — it hides the normalising constant." },
  { g: "≠", name: "Not equal", say: "is not equal to", domain: "grammar", level: "basic",
    means: "The two sides differ.", watch: "" },
  { g: "≪", name: "Much less than", say: "is much less than", domain: "grammar", level: "mid",
    means: "A strong scale separation, usually informal or asymptotic.",
    watch: "Almost never given a threshold. Treat as a modelling assumption, not a fact." },
  { g: "∀", name: "For all", say: "for all", domain: "grammar", level: "basic",
    means: "The statement holds for every element named.",
    watch: "Order matters against ∃ — swapping them changes the claim completely." },
  { g: "∃", name: "There exists", say: "there exists", domain: "grammar", level: "basic",
    means: "At least one element makes the statement true.", watch: "" },
  { g: "⇒", name: "Implies", say: "implies", domain: "grammar", level: "basic",
    means: "If the left holds, the right follows.",
    watch: "Not symmetric, and not causation." },
  { g: "↦", name: "Maps to", say: "maps to", domain: "grammar", level: "mid",
    means: "Shows what one input becomes under a mapping.",
    watch: "Different from →, which relates the whole domain to the whole codomain." },
  { g: "→", name: "Right arrow", say: "to, or tends to", domain: "grammar", level: "basic",
    means: "Source to destination, or a limit being approached.",
    watch: "Three jobs: function signature, limit, and 'becomes'. Read the surroundings." },
  { g: "∴", name: "Therefore", say: "therefore", domain: "grammar", level: "basic",
    means: "The conclusion follows from what came before.", watch: "" },
  { g: "…", name: "Ellipsis", say: "and so on", domain: "grammar", level: "basic",
    means: "A pattern continues in the obvious way.",
    watch: "'Obvious' is doing real work. Check the first and last terms before trusting it." },

  /* ---- sets ---- */
  { g: "∈", name: "Element of", say: "is in, or belongs to", domain: "sets", level: "basic",
    means: "The item is a member of the set.",
    watch: "x ∈ ℝⁿ is the single fastest way to learn a variable's shape." },
  { g: "∉", name: "Not an element of", say: "is not in", domain: "sets", level: "basic",
    means: "The item is not a member.", watch: "" },
  { g: "⊆", name: "Subset", say: "is a subset of", domain: "sets", level: "basic",
    means: "Every element of the left is in the right.",
    watch: "⊂ sometimes means strict, sometimes just subset. Papers disagree." },
  { g: "∪", name: "Union", say: "union", domain: "sets", level: "basic",
    means: "Everything in either set.", watch: "" },
  { g: "∩", name: "Intersection", say: "intersect", domain: "sets", level: "basic",
    means: "Only what is in both.", watch: "" },
  { g: "∅", name: "Empty set", say: "the empty set", domain: "sets", level: "basic",
    means: "The set with no elements.",
    watch: "Not the same as zero, and not the same as undefined." },
  { g: "×", name: "Cartesian product", say: "cross", domain: "sets", level: "mid",
    means: "All ordered pairs from two sets.",
    watch: "Also multiplication and also cross product. Shape context decides." },
  { g: "|·|", name: "Cardinality", say: "the size of", domain: "sets", level: "mid",
    means: "How many elements a set has.",
    watch: "The same bars mean absolute value, determinant, norm, and conditioning." },
  { g: "ℝ", name: "Real numbers", say: "the reals", domain: "sets", level: "basic",
    means: "All real numbers; ℝⁿ is n-dimensional real space.",
    watch: "The superscript is the shape. ℝ^{n×d} is a matrix, not a power." },
  { g: "𝔼", name: "Expectation", say: "the expected value of", domain: "probability", level: "mid",
    means: "The average value of a random quantity.",
    watch: "The subscript says which distribution the average is over — it is not decoration." },

  /* ---- algebra / linear algebra ---- */
  { g: "Σ", name: "Sum", say: "the sum over", domain: "algebra", level: "basic",
    means: "Add up the terms as the index runs over its range.",
    watch: "Check the index bounds before anything else; off-by-one lives here." },
  { g: "∏", name: "Product", say: "the product over", domain: "algebra", level: "basic",
    means: "Multiply the terms together.",
    watch: "Products of probabilities underflow — this is why logs appear immediately after." },
  { g: "ᵀ", name: "Transpose", say: "transpose", domain: "algebra", level: "basic",
    means: "Flip rows and columns.",
    watch: "In attention, QKᵀ is what makes the shapes line up. Track it." },
  { g: "⊙", name: "Hadamard product", say: "element-wise times", domain: "algebra", level: "mid",
    means: "Multiply matching entries, shape unchanged.",
    watch: "Completely different from matrix multiplication — and easy to misread as it." },
  { g: "⊗", name: "Kronecker / outer product", say: "tensor product", domain: "algebra", level: "advanced",
    means: "Builds a larger structure from two smaller ones.", watch: "" },
  { g: "‖·‖", name: "Norm", say: "the norm of", domain: "algebra", level: "mid",
    means: "The length of a vector.",
    watch: "The subscript picks which one. ‖·‖₂ is Euclidean; ‖·‖₁ sums absolute values and induces sparsity." },
  { g: "·", name: "Dot product", say: "dot", domain: "algebra", level: "basic",
    means: "Sum of element-wise products — a similarity score.",
    watch: "This is the operation under attention, cosine similarity, and every retrieval index." },
  { g: "det", name: "Determinant", say: "the determinant of", domain: "algebra", level: "mid",
    means: "The volume scaling factor of a linear map.",
    watch: "Written |A| as often as det(A)." },
  { g: "λ", name: "Eigenvalue / weight", say: "lambda", domain: "algebra", level: "mid",
    means: "An eigenvalue, or a regularisation strength.",
    watch: "Two unrelated jobs. In a loss function it is almost always the regularisation weight." },

  /* ---- calculus ---- */
  { g: "∂", name: "Partial derivative", say: "partial", domain: "calculus", level: "basic",
    means: "Rate of change with respect to one variable, others held fixed.",
    watch: "∂L/∂θ is the whole of backpropagation in one symbol." },
  { g: "∇", name: "Gradient / nabla", say: "grad, or del", domain: "calculus", level: "basic",
    means: "The vector of all partial derivatives — the direction of steepest ascent.",
    watch: "Gradient descent moves against it, hence the minus sign in the update." },
  { g: "∫", name: "Integral", say: "the integral of", domain: "calculus", level: "mid",
    means: "Continuous accumulation over a range.",
    watch: "In ML it is usually an expectation you cannot compute, which is why sampling appears." },
  { g: "d/dx", name: "Total derivative", say: "d by d x", domain: "calculus", level: "basic",
    means: "Rate of change accounting for every path of dependence.",
    watch: "Differs from ∂ exactly when variables depend on each other." },
  { g: "J", name: "Jacobian", say: "the Jacobian", domain: "calculus", level: "advanced",
    means: "The matrix of all first-order partials of a vector function.",
    watch: "Backprop is a chain of Jacobian-vector products, never the full matrix." },

  /* ---- probability ---- */
  { g: "P(·)", name: "Probability", say: "the probability of", domain: "probability", level: "basic",
    means: "How likely an event is.", watch: "p and P are used interchangeably for density and mass. Check the variable type." },
  { g: "|", name: "Given", say: "given", domain: "probability", level: "basic",
    means: "Conditioning: P(A|B) is A's probability once B is known.",
    watch: "The single most overloaded glyph in maths — also absolute value, norm, size, determinant, and set-builder 'such that'." },
  { g: "~", name: "Distributed as", say: "is distributed as", domain: "probability", level: "basic",
    means: "The variable is drawn from that distribution.",
    watch: "x ~ 𝒩(μ, σ²) tells you the sampling procedure, not a value." },
  { g: "𝒩", name: "Normal distribution", say: "normal, or Gaussian", domain: "probability", level: "basic",
    means: "Bell curve with a mean and a variance.",
    watch: "The second argument is variance in most papers but standard deviation in some code. Check." },
  { g: "θ", name: "Parameters", say: "theta", domain: "probability", level: "basic",
    means: "The learnable parameters of a model.",
    watch: "θ vs θ̂: the hat means estimated from data, not the true value." },
  { g: "argmax", name: "Argmax", say: "arg max", domain: "optimization", level: "basic",
    means: "The input that maximises the expression — not the maximum itself.",
    watch: "max gives the value, argmax gives the location. Greedy decoding is argmax over logits." },
  { g: "argmin", name: "Argmin", say: "arg min", domain: "optimization", level: "basic",
    means: "The input that minimises the expression.", watch: "" },
  { g: "≜", name: "Equal by definition", say: "is defined to equal", domain: "grammar", level: "mid",
    means: "Same job as ≔, different house style.", watch: "" },

  /* ---- information theory ---- */
  { g: "H(·)", name: "Entropy", say: "the entropy of", domain: "information", level: "mid",
    means: "Average surprise in a distribution — how uncertain it is.",
    watch: "Base of the log sets the unit: bits for 2, nats for e. Papers usually mean nats." },
  { g: "D_KL", name: "KL divergence", say: "K L divergence", domain: "information", level: "mid",
    means: "How far one distribution is from another.",
    watch: "Not symmetric and not a distance. KL(P‖Q) ≠ KL(Q‖P), and which way round changes behaviour." },
  { g: "I(·;·)", name: "Mutual information", say: "mutual information", domain: "information", level: "advanced",
    means: "How much knowing one variable tells you about another.", watch: "" },
  { g: "log", name: "Logarithm", say: "log", domain: "information", level: "basic",
    means: "Turns products into sums and tames scale.",
    watch: "In ML, log means natural log unless stated. Log-probabilities are always negative." },

  /* ---- neural nets ---- */
  { g: "softmax", name: "Softmax", say: "soft max", domain: "neural", level: "basic",
    means: "Turns a vector of scores into a probability distribution.",
    watch: "Shift-invariant: adding a constant to every logit changes nothing. That is why the max is subtracted for stability." },
  { g: "σ", name: "Sigmoid / std dev", say: "sigma", domain: "neural", level: "basic",
    means: "The logistic function, or a standard deviation.",
    watch: "Lowercase σ is both. Capital Σ is a sum or a covariance matrix. Three symbols, one letter." },
  { g: "ReLU", name: "Rectified linear unit", say: "rel-you", domain: "neural", level: "basic",
    means: "max(0, x) — passes positives, zeroes negatives.", watch: "" },
  { g: "η", name: "Learning rate", say: "eta", domain: "optimization", level: "basic",
    means: "How far each optimizer step moves.",
    watch: "α is used for the same thing about half the time." },
  { g: "ℒ", name: "Loss", say: "the loss", domain: "optimization", level: "basic",
    means: "The objective being minimised.",
    watch: "Some papers maximise a reward and call it 𝒥. Check the sign before comparing." },
  { g: "W, b", name: "Weights and bias", say: "W and b", domain: "neural", level: "basic",
    means: "The affine layer: Wx + b.",
    watch: "Whether W is d_out×d_in or its transpose varies. The shape annotation is the truth." },
  { g: "d_model", name: "Model dimension", say: "d model", domain: "neural", level: "mid",
    means: "The width of the residual stream.",
    watch: "d_head = d_model / n_heads. Nearly every shape in a transformer derives from these two." },
  { g: "√d_k", name: "Attention scaling", say: "root d k", domain: "neural", level: "mid",
    means: "Divides attention scores to keep softmax out of its flat region.",
    watch: "Without it, dot products grow with dimension and gradients vanish." },

  /* ---- inference ---- */
  { g: "T", name: "Temperature", say: "temperature", domain: "inference", level: "basic",
    means: "Divides logits before softmax; higher is flatter and more random.",
    watch: "T → 0 becomes argmax. T = 1 is the model's own distribution." },
  { g: "KV", name: "Key-value cache", say: "K V cache", domain: "inference", level: "mid",
    means: "Stored attention keys and values so past tokens are not recomputed.",
    watch: "Its size grows linearly with sequence length and batch — usually the real memory ceiling." },
  { g: "⌈·⌉", name: "Ceiling", say: "ceiling of", domain: "algebra", level: "basic",
    means: "Round up to the next integer.",
    watch: "Everywhere in block, tile, and page calculations." },
  { g: "⌊·⌋", name: "Floor", say: "floor of", domain: "algebra", level: "basic",
    means: "Round down.", watch: "" },
  { g: "O(·)", name: "Big O", say: "order", domain: "algebra", level: "basic",
    means: "How cost grows as input grows, ignoring constants.",
    watch: "Attention is O(n²) in sequence length — the constant is what every fast kernel actually attacks." },
];
